def gem_config(conf)
  conf.gem :core => "mruby-sprintf"
  conf.gem :mgem => 'mruby-mtest'
  conf.gem :core => "mruby-print"
  conf.gem :core => "mruby-math"
  conf.gem :core => "mruby-time"
  conf.gem :core => "mruby-struct"
  conf.gem :core => "mruby-enum-ext"
  conf.gem :core => "mruby-string-ext"
  conf.gem :core => "mruby-numeric-ext"
  conf.gem :core => "mruby-array-ext"
  conf.gem :core => "mruby-hash-ext"
  conf.gem :core => "mruby-range-ext"
  conf.gem :core => "mruby-proc-ext"
  conf.gem :core => "mruby-symbol-ext"
  conf.gem :core => "mruby-random"
  conf.gem :core => "mruby-object-ext"
  conf.gem :core => "mruby-objectspace"
  conf.gem :core => "mruby-fiber"
  conf.gem :core => "mruby-enumerator"
  conf.gem :core => "mruby-enum-lazy"
  conf.gem :core => "mruby-toplevel-ext"
  conf.gem :core => "mruby-kernel-ext"
  conf.gem :core => "mruby-eval"
  conf.gem :core => "mruby-exit"

  conf.gem :github => "scalone/mruby-hs-regexp"
  conf.gem :mgem => "mruby-io"
  conf.gem :mgem => "mruby-dir"
  conf.gem :mgem => "mruby-tempfile"
  conf.gem :github => "iij/mruby-require"
  conf.gem :github => "cloudwalkio/mruby-socket", :branch => "no-force"
  conf.gem :github => "iij/mruby-pack", :checksum_hash => "88a7fedea413568a1ff0410e109ff55a03b63a5f"
  conf.gem :mgem => "mruby-polarssl"
  conf.gem :mgem => "mruby-qrcode"
  conf.gem :mgem => "mruby-miniz"
  conf.gem :mgem => "mruby-sleep"
  conf.gem :mgem => "mruby-json"
  conf.gem :github => "scalone/mruby-context"
  conf.gem :mgem => "mruby-ripemd"
  conf.gem :mgem => "mruby-hmac"
  conf.gem :mgem => "mruby-sha2"
  conf.gem :github => "scalone/mruby-sha1"
  conf.gem :mgem => "mruby-base58"
  conf.gem :mgem => "mruby-http"

  # be sure to include this gem (the cli app)
  conf.gem File.expand_path(File.dirname(__FILE__))
end

